runtime: go116

instance_class: F1

env_variables:
  APP_ENV: $APP_ENV
  MONGO_URI: $MONGO_URI
  GCP_PROJECTID: $GCP_PROJECTID
  GCP_BUCKETNAME: $GCP_BUCKETNAME
  GCP_API_PREFIX: $GCP_API_PREFIX
  REDIS_ENDPOINT: $REDIS_ENDPOINT
  JWT_SECRET: $JWT_SECRET

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto
