runtime: go116

instance_class: F1

env_variables:
  APP_ENV: ${{ env.APP_ENV }}
  MONGO_URI: ${{ env.MONGO_URI }}
  GCP_PROJECTID: ${{ env.GCP_PROJECTID }}
  GCP_BUCKETNAME: ${{ env.GCP_BUCKETNAME }}
  GCP_SERVICE_ACCOUNT: ${{ env.GCP_SERVICE_ACCOUNT }}
  GCP_API_PREFIX: ${{ env.GCP_API_PREFIX }}

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto
