runtime: go116

instance_class: F1

env_variables:
  APP_ENV: ${{ secrets.APP_ENV }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  GCP_PROJECTID: ${{ secrets.GCP_PROJECTID }}
  GCP_BUCKETNAME: ${{ secrets.GCP_BUCKETNAME }}
  GCP_API_PREFIX: ${{ secrets.GCP_API_PREFIX }}

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto
