name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Deploying to Google Cloud APP Engine
    runs-on: ubuntu-latest
    steps:
      - name: Display GH default env vars
        run: |
          echo "Github act1: $CI"
          echo "Github act2: $GITHUB_ACTOR"
          echo "giyhub act4: ${{ secrets.GCP_PROJECTID }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Google Cloud App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECTID}}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
